# Generated by Django 4.2.11 on 2024-07-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PvModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('abmessung', models.FloatField(blank=True, null=True)),
                ('wirkungsgrad', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quellendatum', models.DateField()),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wechselrichter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle')),
            ],
        ),
        migrations.CreateModel(
            name='Unterkonstruktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tischvariante', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle')),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('art', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
            ],
        ),
        migrations.CreateModel(
            name='QuelleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle')),
            ],
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='quelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle'),
        ),
        migrations.CreateModel(
            name='Preis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('preis', models.IntegerField(blank=True, null=True)),
                ('waehrung', models.CharField(blank=True, max_length=200, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
                ('unterkonstruktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.unterkonstruktion')),
                ('wechselrichter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.wechselrichter')),
            ],
        ),
        migrations.CreateModel(
            name='Nennleistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('leistung', models.FloatField(blank=True, null=True)),
                ('einheit', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
                ('wechselrichter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.wechselrichter')),
            ],
        ),
        migrations.CreateModel(
            name='Hersteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
                ('unterkonstruktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.unterkonstruktion')),
                ('wechselrichter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.wechselrichter')),
            ],
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('degradation', models.FloatField(blank=True, null=True)),
                ('leistungsgarantie', models.IntegerField(blank=True, null=True)),
                ('performancegarantie', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
            ],
        ),
        migrations.CreateModel(
            name='Anzahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('anzahlproPalette', models.IntegerField(blank=True, null=True)),
                ('anzahlproContainer', models.IntegerField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pvModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.pvmodule')),
            ],
        ),
    ]
