# Generated by Django 4.2.11 on 2024-07-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seaeinkauf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datenblatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quellendatum', models.DateField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle')),
            ],
        ),
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quellendatum', models.DateField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaeinkauf.quelle')),
            ],
        ),
    ]
