# Generated by Django 4.2.11 on 2024-05-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weaeinkauf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('laufzeit', models.IntegerField(default=0)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('basisjahr', models.IntegerField(default=0)),
                ('grenzwert', models.FloatField(blank=True, null=True)),
                ('kuendigungsrecht', models.TextField(blank=True, null=True)),
                ('quellen_id', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.quelle')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePreisVerguetung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('jahr', models.IntegerField(default=0)),
                ('indexierung', models.IntegerField(default=0)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('var', models.FloatField(blank=True, null=True)),
                ('fix', models.FloatField(blank=True, null=True)),
                ('minPreis', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicePreis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.servicepreis')),
            ],
        ),
        migrations.CreateModel(
            name='QuelleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('quellen_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.quelle')),
            ],
        ),
    ]
