# Generated by Django 4.2.11 on 2024-05-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weaeinkauf', '0002_servicepreis_servicepreisverguetung_quelledoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepreis',
            name='basisjahr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepreis',
            name='laufzeit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepreisverguetung',
            name='indexierung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepreisverguetung',
            name='jahr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeaPreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('weaTyp_id', models.IntegerField(default=0)),
                ('preis', models.FloatField(blank=True, null=True)),
                ('waehrung', models.CharField(blank=True, max_length=200, null=True)),
                ('transportkosten', models.IntegerField(blank=True, null=True)),
                ('gueltigkeit', models.DateField(blank=True, null=True)),
                ('garantie_verfuegbarkeit', models.CharField(blank=True, max_length=200, null=True)),
                ('quellen_id', models.IntegerField(default=0)),
                ('preis_w_fundament', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.quelle')),
            ],
        ),
        migrations.CreateModel(
            name='WeaFundament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fundament_preis', models.IntegerField(blank=True, null=True)),
                ('weaPreisID', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weaPreis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.weapreis')),
            ],
        ),
        migrations.CreateModel(
            name='WeaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nabenhoehe', models.FloatField(blank=True, null=True)),
                ('turmtyp', models.CharField(blank=True, max_length=200, null=True)),
                ('auslaufdatum', models.DateField(blank=True, null=True)),
                ('genehmigungsunterlagen', models.CharField(blank=True, max_length=200, null=True)),
                ('windklasse', models.CharField(blank=True, max_length=200, null=True)),
                ('weaPreisID', models.IntegerField(default=0)),
                ('gesamthoehe', models.FloatField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weaPreis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.weapreis')),
            ],
        ),
        migrations.CreateModel(
            name='PreisKondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('land', models.CharField(blank=True, max_length=200, null=True)),
                ('wea_anzahl', models.CharField(blank=True, max_length=200, null=True)),
                ('weaPreisID', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weaPreis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weaeinkauf.weapreis')),
            ],
        ),
    ]
