# Generated by Django 4.2.11 on 2024-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaeinkauf', '0003_alter_servicepreis_basisjahr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepreisverguetung',
            name='servicePreisID',
            field=models.IntegerField(default=0),
        ),
    ]
