# Generated by Django 4.2.11 on 2024-05-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaeinkauf', '0004_servicepreisverguetung_servicepreisid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepreis',
            name='alt_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapreis',
            name='alt_id',
            field=models.IntegerField(default=0),
        ),
    ]
